# Generated by Django 3.0.8 on 2020-07-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('edits', models.IntegerField()),
                ('expectations', models.TextField()),
                ('img', models.FileField(upload_to='')),
            ],
        ),
    ]
