# Generated by Django 3.0.8 on 2020-07-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectorify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='edits',
        ),
    ]
